# CMake generated Testfile for 
# Source directory: /global/homes/f/fust1/codes/E3SM/components/eamxx/tests/single-process/gocart
# Build directory: /global/homes/f/fust1/codes/E3SM/components/eamxx/ctest-build/full_debug/tests/single-process/gocart
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(gocart_standalone_np1 "sh" "-c" "srun -n 1 -c 1 --cpu_bind=threads /global/homes/f/fust1/codes/E3SM/components/eamxx/ctest-build/full_debug/bin/test-launcher -- ./gocart_standalone --use-colour no")
set_tests_properties(gocart_standalone_np1 PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" FIXTURES_SETUP "gocart_standalone_generate_output_nc_files_np1_omp1" FULL_TEST_COMMAND "srun -n 1 -c 1 --cpu_bind=threads /global/homes/f/fust1/codes/E3SM/components/eamxx/ctest-build/full_debug/bin/test-launcher -- ./gocart_standalone --use-colour no" LABELS "driver;gocart;physics" PROCESSORS "1" PROCESSOR_AFFINITY "True" RESOURCE_GROUPS "devices:1" _BACKTRACE_TRIPLES "/global/homes/f/fust1/codes/E3SM/externals/ekat/cmake/EkatCreateUnitTest.cmake;345;add_test;/global/homes/f/fust1/codes/E3SM/components/eamxx/cmake/ScreamUtils.cmake;155;EkatCreateUnitTestFromExec;/global/homes/f/fust1/codes/E3SM/components/eamxx/cmake/ScreamUtils.cmake;182;CreateUnitTestFromExec;/global/homes/f/fust1/codes/E3SM/components/eamxx/cmake/ScreamUtils.cmake;191;CreateUnitTest;/global/homes/f/fust1/codes/E3SM/components/eamxx/tests/single-process/gocart/CMakeLists.txt;7;CreateADUnitTest;/global/homes/f/fust1/codes/E3SM/components/eamxx/tests/single-process/gocart/CMakeLists.txt;0;")
add_test(gocart_standalone_np2 "sh" "-c" "srun -n 2 -c 1 --cpu_bind=threads /global/homes/f/fust1/codes/E3SM/components/eamxx/ctest-build/full_debug/bin/test-launcher -- ./gocart_standalone --use-colour no")
set_tests_properties(gocart_standalone_np2 PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" FIXTURES_SETUP "gocart_standalone_generate_output_nc_files_np2_omp1" FULL_TEST_COMMAND "srun -n 2 -c 1 --cpu_bind=threads /global/homes/f/fust1/codes/E3SM/components/eamxx/ctest-build/full_debug/bin/test-launcher -- ./gocart_standalone --use-colour no" LABELS "driver;gocart;physics" PROCESSORS "2" PROCESSOR_AFFINITY "True" RESOURCE_GROUPS "devices:1,devices:1" _BACKTRACE_TRIPLES "/global/homes/f/fust1/codes/E3SM/externals/ekat/cmake/EkatCreateUnitTest.cmake;345;add_test;/global/homes/f/fust1/codes/E3SM/components/eamxx/cmake/ScreamUtils.cmake;155;EkatCreateUnitTestFromExec;/global/homes/f/fust1/codes/E3SM/components/eamxx/cmake/ScreamUtils.cmake;182;CreateUnitTestFromExec;/global/homes/f/fust1/codes/E3SM/components/eamxx/cmake/ScreamUtils.cmake;191;CreateUnitTest;/global/homes/f/fust1/codes/E3SM/components/eamxx/tests/single-process/gocart/CMakeLists.txt;7;CreateADUnitTest;/global/homes/f/fust1/codes/E3SM/components/eamxx/tests/single-process/gocart/CMakeLists.txt;0;")
add_test(gocart_standalone_np3 "sh" "-c" "srun -n 3 -c 1 --cpu_bind=threads /global/homes/f/fust1/codes/E3SM/components/eamxx/ctest-build/full_debug/bin/test-launcher -- ./gocart_standalone --use-colour no")
set_tests_properties(gocart_standalone_np3 PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" FIXTURES_SETUP "gocart_standalone_generate_output_nc_files_np3_omp1" FULL_TEST_COMMAND "srun -n 3 -c 1 --cpu_bind=threads /global/homes/f/fust1/codes/E3SM/components/eamxx/ctest-build/full_debug/bin/test-launcher -- ./gocart_standalone --use-colour no" LABELS "driver;gocart;physics" PROCESSORS "3" PROCESSOR_AFFINITY "True" RESOURCE_GROUPS "devices:1,devices:1,devices:1" _BACKTRACE_TRIPLES "/global/homes/f/fust1/codes/E3SM/externals/ekat/cmake/EkatCreateUnitTest.cmake;345;add_test;/global/homes/f/fust1/codes/E3SM/components/eamxx/cmake/ScreamUtils.cmake;155;EkatCreateUnitTestFromExec;/global/homes/f/fust1/codes/E3SM/components/eamxx/cmake/ScreamUtils.cmake;182;CreateUnitTestFromExec;/global/homes/f/fust1/codes/E3SM/components/eamxx/cmake/ScreamUtils.cmake;191;CreateUnitTest;/global/homes/f/fust1/codes/E3SM/components/eamxx/tests/single-process/gocart/CMakeLists.txt;7;CreateADUnitTest;/global/homes/f/fust1/codes/E3SM/components/eamxx/tests/single-process/gocart/CMakeLists.txt;0;")
add_test(gocart_standalone_np4 "sh" "-c" "srun -n 4 -c 1 --cpu_bind=threads /global/homes/f/fust1/codes/E3SM/components/eamxx/ctest-build/full_debug/bin/test-launcher -- ./gocart_standalone --use-colour no")
set_tests_properties(gocart_standalone_np4 PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" FIXTURES_SETUP "gocart_standalone_generate_output_nc_files_np4_omp1" FULL_TEST_COMMAND "srun -n 4 -c 1 --cpu_bind=threads /global/homes/f/fust1/codes/E3SM/components/eamxx/ctest-build/full_debug/bin/test-launcher -- ./gocart_standalone --use-colour no" LABELS "driver;gocart;physics" PROCESSORS "4" PROCESSOR_AFFINITY "True" RESOURCE_GROUPS "devices:1,devices:1,devices:1,devices:1" _BACKTRACE_TRIPLES "/global/homes/f/fust1/codes/E3SM/externals/ekat/cmake/EkatCreateUnitTest.cmake;345;add_test;/global/homes/f/fust1/codes/E3SM/components/eamxx/cmake/ScreamUtils.cmake;155;EkatCreateUnitTestFromExec;/global/homes/f/fust1/codes/E3SM/components/eamxx/cmake/ScreamUtils.cmake;182;CreateUnitTestFromExec;/global/homes/f/fust1/codes/E3SM/components/eamxx/cmake/ScreamUtils.cmake;191;CreateUnitTest;/global/homes/f/fust1/codes/E3SM/components/eamxx/tests/single-process/gocart/CMakeLists.txt;7;CreateADUnitTest;/global/homes/f/fust1/codes/E3SM/components/eamxx/tests/single-process/gocart/CMakeLists.txt;0;")
add_test(gocart_standalone_np2_vs_np1 "cmake" "-P" "/global/homes/f/fust1/codes/E3SM/components/eamxx/ctest-build/full_debug/bin/CprncTest.cmake" "gocart_standalone_output.INSTANT.nsteps_x1.np2.2021-10-12-45000.nc" "gocart_standalone_output.INSTANT.nsteps_x1.np1.2021-10-12-45000.nc")
set_tests_properties(gocart_standalone_np2_vs_np1 PROPERTIES  FIXTURES_REQUIRED "gocart_standalone_generate_output_nc_files_np1_omp1;gocart_standalone_generate_output_nc_files_np2_omp1" LABELS "gocart;physics;PEM" WORKING_DIRECTORY "/global/homes/f/fust1/codes/E3SM/components/eamxx/ctest-build/full_debug/tests/single-process/gocart" _BACKTRACE_TRIPLES "/global/homes/f/fust1/codes/E3SM/components/eamxx/cmake/CompareNCFiles.cmake;118;add_test;/global/homes/f/fust1/codes/E3SM/components/eamxx/cmake/CompareNCFiles.cmake;195;CompareNCFilesFamily;/global/homes/f/fust1/codes/E3SM/components/eamxx/tests/single-process/gocart/CMakeLists.txt;37;CompareNCFilesFamilyMpi;/global/homes/f/fust1/codes/E3SM/components/eamxx/tests/single-process/gocart/CMakeLists.txt;0;")
add_test(gocart_standalone_np3_vs_np1 "cmake" "-P" "/global/homes/f/fust1/codes/E3SM/components/eamxx/ctest-build/full_debug/bin/CprncTest.cmake" "gocart_standalone_output.INSTANT.nsteps_x1.np3.2021-10-12-45000.nc" "gocart_standalone_output.INSTANT.nsteps_x1.np1.2021-10-12-45000.nc")
set_tests_properties(gocart_standalone_np3_vs_np1 PROPERTIES  FIXTURES_REQUIRED "gocart_standalone_generate_output_nc_files_np1_omp1;gocart_standalone_generate_output_nc_files_np3_omp1" LABELS "gocart;physics;PEM" WORKING_DIRECTORY "/global/homes/f/fust1/codes/E3SM/components/eamxx/ctest-build/full_debug/tests/single-process/gocart" _BACKTRACE_TRIPLES "/global/homes/f/fust1/codes/E3SM/components/eamxx/cmake/CompareNCFiles.cmake;118;add_test;/global/homes/f/fust1/codes/E3SM/components/eamxx/cmake/CompareNCFiles.cmake;195;CompareNCFilesFamily;/global/homes/f/fust1/codes/E3SM/components/eamxx/tests/single-process/gocart/CMakeLists.txt;37;CompareNCFilesFamilyMpi;/global/homes/f/fust1/codes/E3SM/components/eamxx/tests/single-process/gocart/CMakeLists.txt;0;")
add_test(gocart_standalone_np4_vs_np1 "cmake" "-P" "/global/homes/f/fust1/codes/E3SM/components/eamxx/ctest-build/full_debug/bin/CprncTest.cmake" "gocart_standalone_output.INSTANT.nsteps_x1.np4.2021-10-12-45000.nc" "gocart_standalone_output.INSTANT.nsteps_x1.np1.2021-10-12-45000.nc")
set_tests_properties(gocart_standalone_np4_vs_np1 PROPERTIES  FIXTURES_REQUIRED "gocart_standalone_generate_output_nc_files_np1_omp1;gocart_standalone_generate_output_nc_files_np4_omp1" LABELS "gocart;physics;PEM" WORKING_DIRECTORY "/global/homes/f/fust1/codes/E3SM/components/eamxx/ctest-build/full_debug/tests/single-process/gocart" _BACKTRACE_TRIPLES "/global/homes/f/fust1/codes/E3SM/components/eamxx/cmake/CompareNCFiles.cmake;118;add_test;/global/homes/f/fust1/codes/E3SM/components/eamxx/cmake/CompareNCFiles.cmake;195;CompareNCFilesFamily;/global/homes/f/fust1/codes/E3SM/components/eamxx/tests/single-process/gocart/CMakeLists.txt;37;CompareNCFilesFamilyMpi;/global/homes/f/fust1/codes/E3SM/components/eamxx/tests/single-process/gocart/CMakeLists.txt;0;")
